# Generated by Django 5.0.3 on 2024-03-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='romm',
            new_name='room',
        ),
    ]
